name: Deploy to Production

on: 
  push:
    branches: ["main"]

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v2
        run: echo "Hacer Pull del código"
        run: echo "Correr pruebas unitarias"
        run: echo "generar binario"
        run: echo "publicar version"