name: Deploy to Production

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    env:
      MY_ENV_VAR: "Hello World"
    steps:
      -  name: Hola Mundo
         run: echo "${MY_ENV_VAR}"
  
  second-job:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: Hola Mundo 2
        run: echo "Hola Mundo 2"

  third-job:
    runs-on: ubuntu-latest

    steps:
      - name: Working dir
        run: ls -al

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Working dir after checkout
        run: ls -al